apiVersion: v1
kind: Service
metadata:
    name: { { include "cml.name" . } }
    labels: { { - include "cml.labels" . | nindent 4 } }
spec:
    type: { { .Values.service.type } }
    selector: { { - include "cml.selectorLabels" . | nindent 4 } }
    ports:
        - name: http
          port: { { .Values.service.port } }
          targetPort: http
