apiVersion: v2
name: cml-cloud-manager
description: Helm chart for deploying CML Cloud Manager with Redis and MongoDB
type: application
version: 0.1.0
appVersion: '1.0.0'
keywords:
    - cml
    - cloud
    - manager
    - fastapi
    - redis
    - mongodb
maintainers:
    - name: bvandewe
sources:
    - https://github.com/bvandewe/CML-Cloud-Manager
